services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: cashtruck
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5433:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cashtruck
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
