#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/cashtruck
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
#Security
spring.security.oauth2.client.registration.google.client-id=*******
spring.security.oauth2.client.registration.google.client-secret=*******
spring.security.remember-me=*******

#Log
logging.file.path=/
logging.file.name=log.txt
logging.level.com.projects.oleksii.leheza.cashtruck.controllers=info

#Email
spring.mail.host=*******
spring.mail.port=2525
spring.mail.username=*******
spring.mail.password=*******
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#Swagger
springdoc.api-docs.path=/api
springdoc.swagger-ui.path=/swagger.html

#Stripe
STRIPE_SECRET_KEY=*******
STRIPE_PUBLISHABLE_KEY=*******
STRIPE_WEBHOOK_SECRET=*******

